services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.beltalowda.outerbelt.net'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.beltalowda.outerbelt.net'  
    volumes:
      - gitlab-conf:/etc/gitlab/
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - nginx_container_proxynet
      - gitlab_ssh

    ports:
      - "8122:22"
    shm_size: '2gb'
  
volumes:
    gitlab-conf:
    gitlab-logs:
    gitlab-data:

networks:
  nginx_container_proxynet:
    external: true
  gitlab_ssh: