services:
  proxy:
    image: "nginx:1-alpine-slim"
    container_name: proxy
    restart: unless-stopped
    networks: 
      proxy_net:
        ipv4_address: 192.168.222.253
    volumes:
      - nginx-conf:/etc/nginx/
      - nginx-share:/usr/share/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  
volumes:
  nginx-conf:
  nginx-share:

  
networks:
  proxy_net:
    driver: macvlan
    driver_opts:
      parent: enX0
    ipam:
      config:
        - subnet: "192.168.222.0/24"
          ip_range: "192.168.222.0/24"
          gateway: "192.168.222.1"